# Generated by Django 3.1.7 on 2021-04-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210419_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Ссылка на GitHub'),
        ),
    ]
