# Generated by Django 3.1.7 on 2021-03-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210311_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Типы')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'db_table': 'types',
            },
        ),
        migrations.RemoveField(
            model_name='list',
            name='type',
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=50, verbose_name='заголовка'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='list',
            name='types',
            field=models.ManyToManyField(related_name='lists', to='webapp.Types'),
        ),
    ]
