# Generated by Django 3.1.7 on 2021-03-18 10:18

from django.db import migrations, models
import django.db.models.deletion
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210313_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='about_list',
            field=models.TextField(blank=True, null=True, validators=[webapp.validators.MinLengthValidators(5), webapp.validators.str_value]),
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(max_length=300, validators=[webapp.validators.MinLengthValidators(10), webapp.validators.IntegerValidators(str)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lists', to='webapp.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=20, validators=[webapp.validators.MinLengthValidators(2), webapp.validators.IntegerValidators(str)], verbose_name='заголовка'),
        ),
    ]
