# Generated by Django 3.1.7 on 2021-03-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='begin_at',
            field=models.DateField(verbose_name='Дата начало'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
