# Generated by Django 3.1.7 on 2021-04-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('delete_user', 'удаление пользователя из проекта'), ('add_user', 'добавление пользователя в проект')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
